site_name: 'DU CTF 2024'
site_description: 'Writeups for Down Under CTF 2024'
repo_url: https://github.com/sukolenvo/2024duCTF
edit_uri: edit/master/docs
docs_dir: solve

plugins:
  - techdocs-core

nav:
  - 'index.md'
  - Shufflebox: ./shufflebox/index.md
  - Number mashing: ./number_mashing/index.md
  - Intercepted transmissions: ./transmissions/index.md
  - Vector overflow: ./vector/index.md
  - Decrypt then eval: ./decrypt_eval/index.md
  - Yawa: ./yawa/index.md
  - DNAdecay: ./dna/index.md
  - Sign in: ./sign_in/index.md
  - sssshhhh: ./sssshhhh/index.md
  - Rusty vault: ./rusty/index.md
  - Jmp flag: ./jmp_flag/index.md
  - Pac shell: ./pac_shell/index.md
