name: Build & deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build site
        uses: addnab/docker-run-action@v3
        with:
          image: spotify/techdocs:v1.2.4
          options: -v ${{ github.workspace }}:/src -w /src
          run: |
            mkdocs build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: site-files
          path: ./site

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site-files
          path: ./site

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
